// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKRk1gRyc-CaH07pbpERyPb8CfruxyqG8',
    appId: '1:836300643198:web:9f00340090e78923ba712f',
    messagingSenderId: '836300643198',
    projectId: 'flutter-spotify-5f565',
    authDomain: 'flutter-spotify-5f565.firebaseapp.com',
    storageBucket: 'flutter-spotify-5f565.firebasestorage.app',
    measurementId: 'G-N4493ZHPV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIKLBq7eA10p2K_wlKeri_byo9_1kxpcU',
    appId: '1:836300643198:android:9d909f22552dd6f8ba712f',
    messagingSenderId: '836300643198',
    projectId: 'flutter-spotify-5f565',
    storageBucket: 'flutter-spotify-5f565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs5FSG9MalYOB1jsF_hgee4HwHPTySyFg',
    appId: '1:836300643198:ios:1d410065e78c6b34ba712f',
    messagingSenderId: '836300643198',
    projectId: 'flutter-spotify-5f565',
    storageBucket: 'flutter-spotify-5f565.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs5FSG9MalYOB1jsF_hgee4HwHPTySyFg',
    appId: '1:836300643198:ios:1d410065e78c6b34ba712f',
    messagingSenderId: '836300643198',
    projectId: 'flutter-spotify-5f565',
    storageBucket: 'flutter-spotify-5f565.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKRk1gRyc-CaH07pbpERyPb8CfruxyqG8',
    appId: '1:836300643198:web:b136270813902034ba712f',
    messagingSenderId: '836300643198',
    projectId: 'flutter-spotify-5f565',
    authDomain: 'flutter-spotify-5f565.firebaseapp.com',
    storageBucket: 'flutter-spotify-5f565.firebasestorage.app',
    measurementId: 'G-F75R1EXS7N',
  );

}